#!/usr/bin/env bash

declare -x MINIO_ELASTICSEARCH_ENABLE
[[ -z "${MINIO_ELASTICSEARCH_ENABLE}" ]] && MINIO_ELASTICSEARCH_ENABLE="false"

declare -x MINIO_ELASTICSEARCH_FORMAT
[[ -z "${MINIO_ELASTICSEARCH_FORMAT}" ]] && MINIO_ELASTICSEARCH_FORMAT=""

declare -x MINIO_ELASTICSEARCH_URL
[[ -z "${MINIO_ELASTICSEARCH_URL}" ]] && MINIO_ELASTICSEARCH_URL=""

declare -x MINIO_ELASTICSEARCH_INDEX
[[ -z "${MINIO_ELASTICSEARCH_INDEX}" ]] && MINIO_ELASTICSEARCH_INDEX=""
