FROM ghcr.io/dockhippie/golang:1.25-amd64@sha256:f25e3806e58ff056471ad435e6d46f7ad99f0c7af48716834f62930dcf6eb5ac AS build

ENV MINIO_VERSION=RELEASE.2025-10-15T17-29-55Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:b72fb7d0c19fb9f15b0510d87d99cde0626e562b88826894cb500b53ade1fe72

VOLUME ["/var/lib/minio"]
EXPOSE 9000 9001

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
