FROM ghcr.io/dockhippie/golang:1.23-amd64@sha256:eafba8a2dc8efeaf96bf6c2b021a5178c758b079d802d3824fc1a1baf6e7a1e8 AS build

ENV MINIO_VERSION=RELEASE.2025-10-15T17-29-55Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:03bbf25770048db3c6c1f2b19a75714094a82696c51bd2418beafa0ce070911c

VOLUME ["/var/lib/minio"]
EXPOSE 9000 9001

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
