FROM ghcr.io/dockhippie/golang:1.25-arm@sha256:5c96e3ce551244d551935dfa1e5705d01ec1f38d71b5a1fb4f4cb77897bd9ff1 AS build

ENV MINIO_VERSION=RELEASE.2025-10-15T17-29-55Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:2e3b11428d9822ad7d8ca2cc7c8256964250cf2f4ea1a59bbc83daa3479f806f

VOLUME ["/var/lib/minio"]
EXPOSE 9000 9001

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
