#!/usr/bin/env bash

declare -x MINIO_AMQP_ENABLE
[[ -z "${MINIO_AMQP_ENABLE}" ]] && MINIO_AMQP_ENABLE="false"

declare -x MINIO_AMQP_URL
[[ -z "${MINIO_AMQP_URL}" ]] && MINIO_AMQP_URL=""

declare -x MINIO_AMQP_EXCHANGE
[[ -z "${MINIO_AMQP_EXCHANGE}" ]] && MINIO_AMQP_EXCHANGE=""

declare -x MINIO_AMQP_ROUTING_KEY
[[ -z "${MINIO_AMQP_ROUTING_KEY}" ]] && MINIO_AMQP_ROUTING_KEY=""

declare -x MINIO_AMQP_EXCHANGE_TYPE
[[ -z "${MINIO_AMQP_EXCHANGE_TYPE}" ]] && MINIO_AMQP_EXCHANGE_TYPE=""

declare -x MINIO_AMQP_DELIVERY_MODE
[[ -z "${MINIO_AMQP_DELIVERY_MODE}" ]] && MINIO_AMQP_DELIVERY_MODE="0"

declare -x MINIO_AMQP_MANDATORY
[[ -z "${MINIO_AMQP_MANDATORY}" ]] && MINIO_AMQP_MANDATORY="false"

declare -x MINIO_AMQP_IMMEDIATE
[[ -z "${MINIO_AMQP_IMMEDIATE}" ]] && MINIO_AMQP_IMMEDIATE="false"

declare -x MINIO_AMQP_DURABLE
[[ -z "${MINIO_AMQP_DURABLE}" ]] && MINIO_AMQP_DURABLE="false"

declare -x MINIO_AMQP_INTERNAL
[[ -z "${MINIO_AMQP_INTERNAL}" ]] && MINIO_AMQP_INTERNAL="false"

declare -x MINIO_AMQP_NO_WAIT
[[ -z "${MINIO_AMQP_NO_WAIT}" ]] && MINIO_AMQP_NO_WAIT="false"

declare -x MINIO_AMQP_AUTO_DELETED
[[ -z "${MINIO_AMQP_AUTO_DELETED}" ]] && MINIO_AMQP_AUTO_DELETED="false"
