#!/usr/bin/env bash

declare -x MINIO_POSTGRESQL_ENABLE
[[ -z "${MINIO_POSTGRESQL_ENABLE}" ]] && MINIO_POSTGRESQL_ENABLE="false"

declare -x MINIO_POSTGRESQL_FORMAT
[[ -z "${MINIO_POSTGRESQL_FORMAT}" ]] && MINIO_POSTGRESQL_FORMAT=""

declare -x MINIO_POSTGRESQL_CONNECTION_STRING
[[ -z "${MINIO_POSTGRESQL_CONNECTION_STRING}" ]] && MINIO_POSTGRESQL_CONNECTION_STRING=""

declare -x MINIO_POSTGRESQL_TABLE
[[ -z "${MINIO_POSTGRESQL_TABLE}" ]] && MINIO_POSTGRESQL_TABLE=""

declare -x MINIO_POSTGRESQL_HOST
[[ -z "${MINIO_POSTGRESQL_HOST}" ]] && MINIO_POSTGRESQL_HOST=""

declare -x MINIO_POSTGRESQL_PORT
[[ -z "${MINIO_POSTGRESQL_PORT}" ]] && MINIO_POSTGRESQL_PORT=""

declare -x MINIO_POSTGRESQL_USER
[[ -z "${MINIO_POSTGRESQL_USER}" ]] && MINIO_POSTGRESQL_USER=""

declare -x MINIO_POSTGRESQL_PASSWORD
[[ -z "${MINIO_POSTGRESQL_PASSWORD}" ]] && MINIO_POSTGRESQL_PASSWORD=""

declare -x MINIO_POSTGRESQL_DATABASE
[[ -z "${MINIO_POSTGRESQL_DATABASE}" ]] && MINIO_POSTGRESQL_DATABASE=""
