FROM ghcr.io/dockhippie/golang:1.25-amd64@sha256:4cbad21944b6d1176e1e69310a6c9efc86d72402fb29dbe157cd0cefa6a99d71 AS build

ENV MINIO_VERSION=RELEASE.2019-06-01T03-46-14Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:cfbada432541bb5d097f2f126259a989bbb3a2992f3ab437a6ff6316df1fc528

VOLUME ["/var/lib/minio"]
EXPOSE 9000

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
