FROM ghcr.io/dockhippie/golang:1.23-arm@sha256:6ada9ea0779f91ba172bee4ce54f238eb1dbb274719daa34e426d3316e345cf9 AS build

ENV MINIO_VERSION=RELEASE.2019-06-01T03-46-14Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:8c64c1be1746192a96a6fb0eeaa9ae22f0eb07030edeed35cfce269190ee7281

VOLUME ["/var/lib/minio"]
EXPOSE 9000

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
