FROM ghcr.io/dockhippie/golang:1.26-arm64@sha256:44108d8575001eae5991adab1319faad8f3eb433b8924a18748419a1389c1d07 AS build

ENV MINIO_VERSION=RELEASE.2019-06-01T03-46-14Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:c530cedd4b1a3baf515941e342922253b205fdb7cce686d1138db0df6cdb508f

VOLUME ["/var/lib/minio"]
EXPOSE 9000

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
