FROM ghcr.io/dockhippie/golang:1.25-arm64@sha256:7b3c7ad3d5d76f07f319d400bba7efbd1b334c12e4c32b32aa36524a6b2522e7 AS build

ENV MINIO_VERSION=RELEASE.2019-06-01T03-46-14Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:d7813fe27f3eeb726a418182751235f564ab8e965cc6e35d6f676fba29ee05bd

VOLUME ["/var/lib/minio"]
EXPOSE 9000

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
