FROM webhippie/golang:1.10-arm32v6@sha256:79cb9f8ede8610ca002490bc3e0a7d5a5bb3a0d9690f9b1d9e02e7ae725a7dce as build

ENV MINIO_PATH github.com/minio/minio
ENV MINIO_REPO https://${MINIO_PATH}.git
ENV MINIO_BRANCH RELEASE.2018-07-13T00-09-07Z

RUN git clone -b ${MINIO_BRANCH} ${MINIO_REPO} /srv/app/src/${MINIO_PATH} && \
  cd /srv/app/src/${MINIO_PATH} && \
  go install

FROM webhippie/alpine:latest-arm32v6@sha256:e974574e5a59c39564f075610a5e157c9053ed12d809d1c20d724687b2975311

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Minio" \
  org.label-schema.vcs-url="https://github.com/dockhippie/minio.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 9000

VOLUME ["/var/lib/minio"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay ./overlay-arm32v6 /
