FROM webhippie/golang:1.10@sha256:368d59e7dcd55fdca7be8ecd0e197098679e9dca33bf769418c3fcf9e53078fa as build

ENV MINIO_PATH github.com/minio/minio
ENV MINIO_REPO https://${MINIO_PATH}.git
ENV MINIO_BRANCH RELEASE.2018-07-13T00-09-07Z

RUN git clone -b ${MINIO_BRANCH} ${MINIO_REPO} /srv/app/src/${MINIO_PATH} && \
  cd /srv/app/src/${MINIO_PATH} && \
  go install

FROM webhippie/alpine:latest@sha256:a730ba3a4284e5f9b7f0b35cb503b5590869e374ee92ac6c1456da2fd4f9f0e7

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Minio" \
  org.label-schema.vcs-url="https://github.com/dockhippie/minio.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 9000

VOLUME ["/var/lib/minio"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay ./overlay-amd64 /
