FROM ghcr.io/dockhippie/golang:1.23-amd64@sha256:dfb7a5af97bab128270db1b2ff4ef7f4d2e61e893ada566e0aa63bf8257efe45 AS build

RUN apk add --no-cache perl && \
  git clone -b master https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:458f51fa9c24d94a87ced39f652ba8d2eec710748c738a174e88c5a8f133a85b

VOLUME ["/var/lib/minio"]
EXPOSE 9000 9001

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
