FROM ghcr.io/dockhippie/golang:1.23-arm@sha256:dd89946ad837197c6d77bb1ec7efd0df23faaf9c9fa75490c4593c7456463b86 AS build

RUN apk add --no-cache perl && \
  git clone -b master https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:147c30af4d302c2e4f1bd6afd0f27fc0796d160795a436fa6641264512beb2f8

VOLUME ["/var/lib/minio"]
EXPOSE 9000 9001

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
