FROM ghcr.io/dockhippie/golang:1.23-arm@sha256:1bfba8f05cb03bc5854cbaf698a10f89b0b5ffe77ebc38297cd36c049d601b60 AS build

ENV MINIO_VERSION=RELEASE.2025-07-23T15-54-02Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:a0286af018ea4a63ae0db03ba2596128e761417663c397747960786136622119

VOLUME ["/var/lib/minio"]
EXPOSE 9000 9001

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
