FROM ghcr.io/dockhippie/golang:1.26-amd64@sha256:0543d97ccfffbdfbb83fcdaec895a39c2c14e4a1138a077c8182b4a1bbc40eb4 AS build

ENV MINIO_VERSION=RELEASE.2025-07-23T15-54-02Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:f74042fd7f00bbdaa91c30b3c2b98d094defd88a4164c41fb20db2e613cbc827

VOLUME ["/var/lib/minio"]
EXPOSE 9000 9001

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
