FROM ghcr.io/dockhippie/golang:1.23-amd64@sha256:bc20bd508ca7a8897e196ba333eeb7afa05e98dbc1e9557a3890e74e71740877 as build

ENV MINIO_PATH github.com/minio/minio
ENV MINIO_REPO https://${MINIO_PATH}.git
ENV MINIO_BRANCH RELEASE.2019-12-19T22-52-26Z

RUN git clone -b ${MINIO_BRANCH} ${MINIO_REPO} /srv/app/src/${MINIO_PATH} && \
  cd /srv/app/src/${MINIO_PATH} && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:05ec00e6f98fabfc56613b60cbd1e09ffed15c93904aadc18cd0703dd45b2602

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Minio" \
  org.label-schema.version="2019-10-12" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 9000

VOLUME ["/var/lib/minio"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay ./overlay-amd64 /
