FROM ghcr.io/dockhippie/golang:1.25-arm@sha256:f9c293f227f478bec852d0c993752cb3fd344e273fb0431d7183b64ffe30d69f AS build

ENV MINIO_VERSION=RELEASE.2019-10-12T01-39-57Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:ed2086064b6d9258c7371e1de328006553a2434b565477a39204e62cbff829f7

VOLUME ["/var/lib/minio"]
EXPOSE 9000

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
