FROM ghcr.io/dockhippie/golang:1.23-arm64@sha256:77803518846e272584a3a22cc0172def69a88fe74060ccd6ee8928af77219c5f AS build

ENV MINIO_VERSION=RELEASE.2019-10-12T01-39-57Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:bf2c966548f93edeee7a9dfc03b98f1ed7ed9ccd6503b50912be86b486d16fc8

VOLUME ["/var/lib/minio"]
EXPOSE 9000

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
