FROM ghcr.io/dockhippie/golang:1.25-amd64@sha256:3b88dc1dcc9c5b70b9d176d54b4d6fd1555365bd40166d5fa277c348f1e827fa AS build

ENV MINIO_VERSION=RELEASE.2019-10-12T01-39-57Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:5b037c077d4ba74ae7da3a97e0f4a5caff892dfae63bc2ca2f9053a46f6c40d7

VOLUME ["/var/lib/minio"]
EXPOSE 9000

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
