FROM ghcr.io/dockhippie/golang:1.23-arm@sha256:75c9e55666b602a95a739b89ee83c93e9f069e8444fe28fb2cebc4f9a5588839 AS build

ENV MINIO_VERSION=RELEASE.2019-10-12T01-39-57Z

RUN apk add --no-cache perl && \
  git clone -b ${MINIO_VERSION} https://github.com/minio/minio.git /srv/app/src && \
  cd /srv/app/src && \
  make install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:8253d93cf993bf7d69fcacebb3da4454d5b138325ddf51a0881df39b0df86007

VOLUME ["/var/lib/minio"]
EXPOSE 9000

WORKDIR /var/lib/minio
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/minio && \
  groupadd -g 1000 minio && \
  useradd -u 1000 -d /var/lib/minio -g minio -s /bin/bash -M minio && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay /
