#!/usr/bin/env bash

declare -x MINIO_REDIS_ENABLE
[[ -z "${MINIO_REDIS_ENABLE}" ]] && MINIO_REDIS_ENABLE="false"

declare -x MINIO_REDIS_FORMAT
[[ -z "${MINIO_REDIS_FORMAT}" ]] && MINIO_REDIS_FORMAT=""

declare -x MINIO_REDIS_ADDRESS
[[ -z "${MINIO_REDIS_ADDRESS}" ]] && MINIO_REDIS_ADDRESS=""

declare -x MINIO_REDIS_PASSWORD
[[ -z "${MINIO_REDIS_PASSWORD}" ]] && MINIO_REDIS_PASSWORD=""

declare -x MINIO_REDIS_KEY
[[ -z "${MINIO_REDIS_KEY}" ]] && MINIO_REDIS_KEY=""
