FROM ghcr.io/dockhippie/golang:1.25-amd64@sha256:cb35999106a3936c64ae435313f024c129db790105159e030299477809a95f70 as build

ENV MINIO_PATH github.com/minio/minio
ENV MINIO_REPO https://${MINIO_PATH}.git
ENV MINIO_BRANCH RELEASE.2020-01-16T03-05-44Z

RUN git clone -b ${MINIO_BRANCH} ${MINIO_REPO} /srv/app/src/${MINIO_PATH} && \
  cd /srv/app/src/${MINIO_PATH} && \
  GO111MODULE=on go install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:f2a9d34a6b2c077d31fc74f1fbbe34481ae06cabd73564890c83df1b9f7edcbf

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Minio" \
  org.label-schema.version="2019-10-12" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 9000

VOLUME ["/var/lib/minio"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/minio /usr/bin/minio
COPY ./overlay ./overlay-amd64 /
